### ISSUE TITLE
Helpdesk info

### ISSUE THREAD

**Issue by abhijna** [nih-cfde/public-website-content#28]
Hi @kloydrti @ACharbonneau

We're starting to set up a (Jira) helpdesk to route questions to. Here's the widget code for the public website:

```
<script data-jsd-embedded data-key="94fd264d-68ff-4fc4-9c6e-d34f1da0fa05"
data-base-url="https://jsd-widget.atlassian.com" src="
https://jsd-widget.atlassian.com/assets/embed.js"></script>
```

We're thinking of including it in the header of the training website. But the placement is not final yet.

**Comment by jacko13** [comment]
Are there any updates on this issue? I don't see any Help Desk links in the header of the training site.
Are we still wanting to add a similar link to the CFDE public site?

**Comment by ACharbonneau** [comment]
I don't think it happened on training, but if it can go in this website that would be great

**Comment by jacko13** [comment]
Thanks for clarifying Amanda. I will look into it.

**Comment by jacko13** [comment]
This has been added to the Development site.
I made it so that it's only shown when users log in, or in other words, it's only available for the Private Site - I hope that's okay? Please let me know whether anyone (public) should be able to ask questions and contact us. I was thinking this way, we could avoid spam/hack/phishing attempts and only focus on our real actual users questions. But let me know if you want this public.
I also submitted a question to test it. I'm hoping someone gets back to me with confirmation that the Contact Us widget goes to some Jira related question list.

**Comment by jacko13** [comment]
This has been pushed live - 12/16/2021 at roughly 12.20pm.
Can someone close this ticket? It's done.

**Comment by ACharbonneau** [comment]
I have updated your permissions so you can close things. In the future please just tell me if something is not working as it should
