### ISSUE TITLE
time zones in the calendar 

### ISSUE THREAD

**Issue by jeremywalter** [nih-cfde/public-website-content#43]
events on the calendar show up defaulted to the time zone they were entered in as... I believe this will probably cause confusion in the long-run and it might be worth addressing so, either by engineering the website to reflect time zones for the user (best case), or choosing a time zone for the website (PST or EST)...

**Comment by abhijna** [comment]
Just to clarify Jeremy's point:

Each event has a time zone specified. See example below
<img width="888" alt="Screen Shot 2021-04-12 at 11 54 39 AM" src="https://user-images.githubusercontent.com/6900555/114446928-9ef96700-9b86-11eb-9582-8bb36bd4a7e5.png">

Some are displayed in EDT and some are in PDT (based on who made it and which time zone they were in). 
It is fully functional as is. However, it would be great if we could keep the timezone displayed on the event page consistent. Because a user in CA might see one event in PDT and assume all listed events are in PDT without paying attention to the timezone for the next event they are trying to enroll in.

**Comment by lance1572** [comment]
This should be entered by the user. By making a default time zone, it would undoubtedly cause confusion for those in differing time zones. Apparently, it is defaulted to New York. Changing the default will override all event timezones published.
